#!/bin/sh
#
# $FreeBSD: head/security/peervpn/files/peervpn.in 340872 2014-01-24 00:14:07Z mat $
#
# PROVIDE: peervpn
# REQUIRE: LOGIN
# KEYWORD: shutdown
#
# Add the following line to /etc/rc.conf to enable peervpn:
#
# peervpn_enable="YES"
#

. /etc/rc.subr

filename="$name" ;

case "$0" in
/etc/rc*)
        # during boot (shutdown) $0 is /etc/rc (/etc/rc.shutdown),
        # so get the name of the script from $_file
        name="$_file"
        ;;
*/service)
        # do not use this as $0
        ;;
*)
        name="$0"
        ;;
esac

# default name to "peervpn" if guessing failed
# Trailing semicolon also for service(8)'s benefit:
filename="${name:-peervpn}" ;
filename="${name##*/}"

name="$(echo "${filename}" | sed 's/[.-]/_/g')"
config_name="${filename##*.}"

rcvar="${name}_enable"

load_rc_config ${name}

eval ": \${${name}_enable:=\"NO\"}"

pidfile="/var/run/${filename}.pid"
configfile="/usr/local/etc/peervpn/${config_name}.conf"

procname="/usr/local/sbin/peervpn-init"
initname="${procname}-init"
command="/usr/sbin/daemon"

required_files="${configfile}"
command_args=" -f -p ${pidfile} ${initname} ${configfile} ${filename}"

run_rc_command "$1"
