#!/bin/sh

user=$(whoami)
current_branch=$(git branch | sed -n '/\* /s///p')
date=$(date)

git fetch origin

git add -A

if [ $current_branch != $user ]; then
  git stash
  
  git branch --set-upstream-to=origin/$user $user
  git checkout $user

  git stash pop
fi

git commit -m "$date: regular scripts update"

git push

exit 0
