#!/bin/sh

hostname=$(hostname)

verbosity=">&/dev/null"
interface=wlp3s0
wpaconf="/etc/wpa_supplicant.conf"
essid=""
dhcp=dhclient
checkhost=www.google.de

open=false
save=false
quiet=false

function main {
  if ! checkSyntax; then
    failecho "please check your call syntax!"
    exit 1
  fi

  greenecho "pinging $checkhost .."
  if checkConnection; then
    successecho "$hostname is already connected, nothing to do here!"
    exit 0
  fi

  failecho "$hostname is not connected!"

  greenecho "checking rfkill for software block.."
  if checkBlock; then
    failecho "wifi device seems to be blocked, trying to unblock"
    unblock
  fi

  greenecho "terminating old services.."
  disconnect

  greenecho "starting relevant services.."
  connect

  if checkConnection; then
    successecho "connection successfully established!"
    if $save; then
      greenecho "saving current configuration.."
      save
    fi
    successecho "exiting wconnect"
    exit 0
  else
    failecho "could not connect! see 'journalctl -xn' or enhance verbosity for more info"
    failecho "exiting wconnect"
    exit 1
  fi
}

function checkSyntax {
  if $open; then
    if [ -z "$essid" ]; then
      return 1
    fi
  fi

  return 0
}

function checkConnection {
  if sh -c "ping -c 1 -W 2 $checkhost $verbosity"; then
    return 0
  fi

  return 1
}

# Check if wifi is blocked and return 0 if true
function checkBlock { 
  if sh -c "sudo rfkill list wifi | grep yes $verbosity"; then
    return 0
  fi

  return 1
}

function unblock {
  sh -c "sudo rfkill unblock wifi $verbosity"
}

function startDaemon {
  if sh -c "sudo systemctl start wconnect@"$interface".service $verbosity"; then
    return 0
  fi

  return 1
}

function stopDaemon {
  if sh -c "sudo systemctl stop wconnect@"$interface".service $verbosity"; then
    return 0
  fi

  return 1
}

function startWPA {
  #if sudo systemctl start wpa_supplicant@"$interface".service; then
  if sh -c "sudo systemctl start wpa_supplicant@"$interface".service $verbosity"; then
    return 0
  fi

  return 1
}

function stopWPA {
  #if sudo systemctl stop wpa_supplicant@"$interface".service; then
  if sh -c "sudo systemctl stop wpa_supplicant@"$interface".service $verbosity"; then
    return 0
  fi

  return 1
}

function startDHCP {
  #if sudo systemctl start $dhcp@"$interface".service; then
  if sh -c "sudo systemctl start $dhcp@"$interface".service $verbosity"; then
    return 0
  fi

  return 1
}

function stopDHCP {
  #if sudo systemctl stop $dhcp@"$interface".service; then
  if sh -c "sudo systemctl stop $dhcp@"$interface".service $verbosity"; then
    return 0
  fi

  return 1
}

function startIWCONFIG {
  if sudo iwconfig $interface essid $essid; then
    return 0
  fi

  return 1
}

#function stopIWCONFIG {
  # TODO ?
#}

function connect {
  if $open; then
    startIWCONFIG
  else
    startWPA
  fi

  startDHCP
  #startDaemon
}

function disconnect {
  #stopDaemon  
  stopDHCP
  stopWPA
#  stopIWCONFIG
}

function reconnect {
  disconnect
  connect
}

function help {
  echo -e "usage: wconnect [COMMANDS]\n
    possible commands are:\n 
    \t-e provide an essid to connect to 
    \t-h this help message
    \t-i specify interface
    \t-o open network (requires a essid)
    \t-q quiet mode
    \t-r force reconnect 
    \t-s save used configuration (todo)
    \t-v verbosity: 0 - nothing, 1 - stdout, 2 - stdout & stderr
    \t-x terminate connection\n"
}

prefix="••"

function greenecho () { 
  echo -e "\033[1;34m${prefix}\033[0m\033[1;32m $@\033[0m"
}

function redecho () { 
  echo -e "\033[1;34m${prefix}\033[0m\033[1;31m $@\033[0m"
}

function successecho () { 
  echo -e "\033[1;34m${prefix}\033[0m\033[1;38m $@\033[0m"
}

function failecho () { 
  echo -e "\033[1;34m${prefix}\033[0m\033[1;31m $@\033[0m"
}

while getopts "e:hi:oqrsv:x" optname
  do
    case "$optname" in
      "e")
        essid=$OPTARG
        ;;
      "h")
        help
        exit 0
        ;;
      "i")
        interface=$OPTARG
        ;;
      "o")
        open=true
        ;;
      "q")
        quiet=true
        ;;
      "r")
        disconnect
        ;;
      "s")
        save=true
        ;;
      "v")
        case "$OPTARG" in
          0)
            verbosity=">&/dev/null"
            ;;
          1)
            verbosity="2>/dev/null"
            ;;
          2)
            verbosity=""
            ;;
          *)
            failecho "only values 0,1 and 2 are allowed. Defaulting to 0 (no output)"
            ;;
        esac
        ;;
      "x")
        disconnect
        exit 0
        ;;
      "?")
        failecho "Unknown option $OPTARG"
        exit 1
        ;;
      ":")
        failecho "No argument value for option $OPTARG"
        exit 1
        ;;
      *)
        # Should not occur
        failecho "Unknown error while processing options"
        exit $?
        ;;
    esac
  done

if $quiet; then
  main >&/dev/null
else
  main
fi
