#!/bin/sh

interface=wlp3s0""
wpaSupConfig=""
save=false

function main {
  if checkConnection; then
    successecho "Computer is already connected, try to force reconnection with -r"
    exit 0
  fi

  if checkBlock; then
    rfkill unblock wifi
  fi

  disconnect

  if connect; then
    if $save; then
      save
    fi
    exit 0
  else
    exit 1
  fi
}

function determineSuccess {
  if checkConnection; then
    successecho "Successfully connected wireless network, have fun!"
    return 0
  else
    failecho "Could not connect, check 'systemctl status wconnect@"$interface".service' or 'journalctl -xn' for info"
    return 1
  fi
}

# Check if wifi is blocked and return 0 if true
function checkBlock { 
  greenecho "checking rfkill for software block.."

  rfkill list wifi 

  if [ $? == 0 ]; then
    return 0
  else
    return 1
  fi
}

function connect {
  greenecho "attempting to start wconnect@"$interface".service"
  sudo systemctl start wconnect@"$interface".service

  determineSuccess
  return $?
}

function reconnect {
  greenecho "attempting to reconnect to wireless network.." 
  sudo systemctl restart wconnect@"$interface".service

  if determineSuccess; then
    return 0
  else
    return 1
  fi
}

function disconnect {
  greenecho "attempting to disconnect wireless network.." 
  sudo systemctl stop wconnect@"$interface".service
}

function checkConnection {
  if ping -c 1 -W 2 www.google.de >&/dev/null; then
    return 0
  else
    return 1
  fi
}

function help {
  echo -e "usage: scriptSetup [COMMANDS]\n
    possible commands are:\n 
    \t-c configure systemd files
    \t-h this help message
    \t-i specify interface
    \t-r force reconnect 
    \t-s save used configuration
    \t-x terminate connection\n"
}

prefix="••"

function greenecho () { 
  echo -e "\033[1;34m${prefix}\033[0m\033[1;32m $@\033[0m"
}

function redecho () { 
  echo -e "\033[1;34m${prefix}\033[0m\033[1;31m $@\033[0m"
}

function successecho () { 
  echo -e "\033[1;34m${prefix}\033[0m\033[1;38m $@\033[0m"
}

function failecho () { 
  echo -e "\033[1;34m${prefix}\033[0m\033[1;31m $@\033[0m"
}

while getopts "c:hi:rsx" optname
  do
    case "$optname" in
      "c")
        wpaSupConfig=$OPTARG
        ;;
      "h")
        help
        exit 0
        ;;
      "i")
        interface=wlp3s0$OPTARG
        ;;
      "r")
        reconnect
        exit $?
        ;;
      "s")
        save=true
        ;;
      "x")
        disconnect
        exit 0
        ;;
      "?")
        failecho "Unknown option $OPTARG"
        exit 1
        ;;
      ":")
        failecho "No argument value for option $OPTARG"
        exit 1
        ;;
      *)
        # Should not occur
        failecho "Unknown error while processing options"
        exit $?
        ;;
    esac
  done

main
