#!/bin/sh

function infWconnect {
  while true; do
    wconnect
    sleep 10
  done
}

# runs when out of sleep
case / in
  pre/*)
    exit 0
    ;;
  post/*)
    tries=0
    
    while !(wconnect); do
      if [ tries -gt 3 ]; then
        echo "Connection could not be established, see logs for more!"
        exit 1
      fi
      let tries=tries+1 
    done

    echo "Reconnect successful or connection already established!"
    exit 0
    ;;
esac

infWconnect &
