#!/bin/bash

[ $EUID -ne 0 ] && exit "Needs root to run"

error() { echo "$@" && exit 1; }
info() { echo && echo ".. $@ .."; }

confirm() {
  local ANSWER
  printf "$1 [y]/n " && read -r ANSWER

  case $ANSWER in
    n|N|no|No|NO)
      return 1 ;;
    *)
      return 0 ;;
  esac
}

eix-sync

eselect news read

echo && confirm "continue?" || exit 1

info "running package update"

emerge -avuDN --with-bdeps y @world || error "package update failed"

# info "running etc-update"
#
# etc-update || error "etc-update failed"

if command -v lafilefixer; then
  info "running lafilefixer"

  lafilefixer --justfixit || error "lafilefixer failed"
fi

info "running depclean"

emerge -av --depclean || error "depclean failed"

info "running revdep-rebuild"

revdep-rebuild || error "revdep-rebuild failed"

info "running eclean"

eclean -d distfiles || error "eclean failed"
