#!/bin/sh

date=$(date +'%d. %B %Y')
rechnungs_file=~/Work/rechnung.tex

wageperhour="12.00"
month="September"
year="2013"
hours=30

sed -i "s/{date}{[0-9]*. [a-z A-Z]* [0-9]*}/{date}{$date}/" $rechnungs_file 

sed -i "s/\\\Artikel{[0-9]*}{\\\raggedright{Java Development}}{[0-9]*.[0-9]*}/\\\Artikel{$hours}{\\\raggedright{Java Development}}{$wageperhour}/" $rechnungs_file 
sed -i "s/Zeitraum der Leistungserbringung: [a-z A-Z]* [0-9]*/Zeitraum der Leistungserbringung: $month $year/" $rechnungs_file
sed -i "s/Gesamtanzahl der erbrachten Stunden: [0-9]*/Gesamtzahl der erbrachten Stunden: $hours/" $rechnungs_file

pdflatex -output-directory ~/Work $rechnungs_file
