#!/bin/bash
# wconnect.sh -- created 2013-09-03, Aljosha Friemann
# @Last Change: 24-Dez-2004.
# @Revision:    0.0

wireless_device=""
verbosity=""
dhcp=dhclient
quiet=false

# echo colours and format
function greenecho () { 
  echo -e "\033[1;34m${prefix}\033[0m\033[1;32m $@\033[0m" 
}

function redecho () { 
  echo -e "\033[1;34m${prefix}\033[0m\033[1;31m $@\033[0m" 
}

function successecho () { 
  echo -e "\033[1;34m${prefix}\033[0m\033[1;38m $@\033[0m" 
}

function failecho () { 
  echo -e "\033[1;34m${prefix}\033[0m\033[1;31m $@\033[0m" 
}

function root {
  if [ "$UID" != 0 ]; then 
    me=$(dirname $0)/$(basename $0)
    successecho "executing $me as root"
    sudo $me
    exit 0
  fi

  return 0
}

function detectWirelessDevice {
  greenecho "Attempting to detect wireless interface.."
 
  saveIFS=$IFS

  IFS=$'\n' read wifi0 wifi1 wifi2 <<< "$(ip link | grep -o "w[a-z 0-9]*[0-9]")"

  if [ -z $wifi0 ]
  then
    redecho "Can't detect wireless interface, please enter device name: "
    read wireless_device
    return 0
  fi

  if [ -z $wifi1 ]
  then
    wireless_device=$wifi0 
  else
    if [ -z $wifi2 ]
    then
      greenecho "Available wireless interfaces: $wifi0 | $wifi1 - enter device name: "
    else
      greenecho "Available wireless interfaces: $wifi0 | $wifi1 | $wifi2 - enter device name: "
    fi

    read wireless_device
  fi

  IFS=$saveIFS
  
  successecho "Set wireless device name to $wireless_device"

  return 0
}

function connect {
  wpa_supplicant -B -Dwext -c /etc/wpa_supplicant.conf -i $wireless_device
  $dhcp $wireless_device
}

function disconnect {
  wpa_cli terminate
  $dhcp -x
}

function connected {
  if ping -c 1 -W 1 www.google.de &>/dev/null; then
    return 0
  fi

  return 1
}

function main {
  if connected $verbosity; then
    greenecho "already connected, try reconnecting if you really want to."
    exit 0
  fi

  root

  detectWirelessDevice $verbosity

  tries=0
  success=0

  greenecho "trying to connect.."

  while [[ tries -lt 3 ]];
  do
    connect $verbosity
    if connected $verbosity; then
      success=1
      break 
    fi
    disconnect $verbosity
    let tries=tries+1
  done

  if [ $success ]; then
    successecho "connection established, have fun!"
    return 0
  fi

  failecho "could not establish connection.."
  return 1
}

function help {
  echo -e "usage: wconnect [COMMANDS]\n
    possible commands are:\n 
    \t-h this help message
    \t-i specify interface
    \t-q quiet mode
    \t-r force reconnect 
    \t-v verbosity: 0 - nothing, 1 - stdout, 2 - stdout & stderr
    \t-x terminate connection\n"
}

while getopts "hi:qrv:x" optname
do
  case "$optname" in
    "h")
      help
      exit 0
      ;;
    "i")
      interface=$OPTARG
      ;;
    "q")
      quiet=true
      ;;
    "r")
      disconnect
      ;;
    "v")
      case "$OPTARG" in
        0)
          verbosity=">&/dev/null"
          ;;
        1)
          verbosity="2>/dev/null"
          ;;
        2)
          verbosity=""
          ;;
        *)
          failecho "only values 0,1 and 2 are allowed. Defaulting to 1 (only stdout)"
          verbosity="&>/dev/null"
          ;;
      esac
      ;;
    "x")
      disconnect
      exit 0
      ;;
    "?")
      failecho "Unknown option $OPTARG"
      exit 1
      ;;
    ":")
      failecho "No argument value for option $OPTARG"
      exit 1
      ;;
    *)
      # Should not occur
      failecho "Unknown error while processing options"
      exit $?
      ;;
  esac
done


if $quiet; then
  main >/dev/null
else
  main
fi

exit 0
