#!/bin/sh

ACTION=$1

INPUT=$2
OUTPUT=$3
PASSWORD_FILE=$4

help() {
    echo -e "usage:\n\t$0 encrypt|decrypt FILE OUTPUT KEYFILE"
}

encrypt() {
    local PASS=$2

    openssl enc -aes-256-cbc -in "$INPUT" -out "${INPUT}.enc" -k "$PASS"
}

decrypt() {
    local PASS=$2

    openssl enc -d -aes-256-cbc -in "$INPUT" -out "${INPUT}.gpg" -k "$PASS"
}

[ ! -r "$PASSWORD_FILE" ] && echo "no such file: $PASSWORD_FILE" && help && exit 1

case $ACTION in
    encrypt)
        encrypt "$(cat $PASSWORD_FILE)"
        ;;
    decrypt)
        decrypt "$(cat $PASSWORD_FILE)"
        ;;
esac
