#!/bin/sh

help() {
    echo -e "usage:\n\t$0 encrypt|decrypt FILE OUTPUT KEYFILE"
}

encrypt() {
    local PASS="$1"

    openssl enc -aes-256-cbc -in "$INPUT" -out "${OUTPUT}" -k "$PASS"

    if [ $? -ne 0 ]; then
        rm "$OUTPUT" && return 1
    fi
}

decrypt() {
    local PASS="$1"

    openssl enc -d -aes-256-cbc -in "$INPUT" -out "${OUTPUT}" -k "$PASS"

    if [ $? -ne 0 ]; then
        rm "$OUTPUT" && return 1
    fi
}

ACTION="$1"

INPUT="$2"
OUTPUT="$3"
PASSWORD_FILE="$4"

[ -z "$ACTION" -o -z "$INPUT" -o -z "$OUTPUT" ] && help && exit 1
[ ! -r "$PASSWORD_FILE" ] && echo "no such file: $PASSWORD_FILE" && help && exit 1

case $ACTION in
    encrypt)
        encrypt "$(cat $PASSWORD_FILE)"
        ;;
    decrypt)
        decrypt "$(cat $PASSWORD_FILE)"
        ;;
esac
