#!/bin/bash

TIMEOUT="${BLOCK_TIMEOUT:-2}"
TARGET="${BLOCK_TARGET:-1.1.1.1}"

if nc -znw"$TIMEOUT" "$TARGET" 53 &>/dev/null; then
  echo -e "online\nonline\nonline"
  exit
fi

echo -e "offline\noffline\noffline"
