#!/bin/bash

TIMEOUT="${BLOCK_TIMEOUT:-2}"
TARGET="${BLOCK_TARGET:-1.1.1.1}"

ROUTES="$(ip route get "${TARGET}/32")"

STATUS=offline

if [ -n "$ROUTES" ]; then
  if nc -n -w"$TIMEOUT" "$TARGET" 53 &>/dev/null; then
    STATUS=online
  fi
fi

echo -n "$STATUS"
