#!/bin/sh

coffee() {
  case $1 in
    on)
      xset s off
      xset -dpms
      usv stop xscreensaver
      ;;
    off)
      xset s on
      xset +dpms
      usv start xscreensaver
      ;;
    *)
      echo "usage: coffee on|off" && return 0
      ;;
  esac
}

coffee $@
