#!/bin/bash

PID=$(pgrep --newest dbus-launch)

import_environment() {
  ((PID)) && for var; do
    IFS='=' read key val < <(egrep -z "^$var" /proc/$PID/environ)

    if [ -z "$key" ] || [ -z "$val" ]; then
      continue
    fi

    printf -v "$key" %s "$val"
    [[ ${!key} ]] && echo "export $key=$val"
  done
}

import_environment XAUTHORITY HOME USER DISPLAY XDG_RUNTIME_DIR
