#!/bin/bash

PRIMARY="${PRIMARY:-$( xrandr  | grep primary | awk '{ print $1 }' )}"

help() {
  echo "exd on|off"
}

connected-displays() {
  xrandr | grep " connected" | awk '{ print $1 }'
}

get-display() {
  xrandr | grep "^$1"
}

is-active() {
  # eDP1 connected primary 2560x1440+0+0 (normal left inverted right x axis y axis) 310mm x 170mm
  # HDMI1 connected (normal left inverted right x axis y axis)
  local WORDS=$(get-display "$1" | wc -w)

  [[ $WORDS -gt 10 ]]
}

active-displays() {
  for display in $(connected-displays); do
    if is-active $display; then
      echo "$display"
    fi
  done
}

mode() {
  if is-active "$1"; then
    get-display "$1" | awk '{ print $4 }'
  fi
}

single-lo() {
  echo "turning $1 on left of $PRIMARY"
  xrandr --output "$1" --auto --left-of "$PRIMARY"
}

single-ro() {
  echo "turning $1 on right of $PRIMARY"
  xrandr --output "$1" --auto --right-of "$PRIMARY"
}

single-off() {
  echo "turning $1 off"
  xrandr --output "$1" --off
}

lo() {
  for display in $(connected-displays); do
    case $display in
      "$PRIMARY") continue ;;
      *) single-lo $display ;;
    esac
  done
}

ro() {
  for display in $(connected-displays); do
    case $display in
      "$PRIMARY") continue ;;
      *) single-ro "$display" ;;
    esac
  done
}

toggle() {
  for display in $(connected-displays); do
    case $display in
      "$PRIMARY") continue ;;
      *)
        if is-active $display; then
          single-off "$display"
        else
          single-lo "$display"
        fi
        ;;
    esac
  done
}

on() { lo; }

off() {
  for display in $(connected-displays); do
    case $display in
      "$PRIMARY") echo "keeping $PRIMARY" ;;
      *) single-off "$display" ;;
    esac
  done
}

if [[ -z "$@" ]]; then
  toggle
else
  $@
fi
