#!/bin/bash

PRIMARY="${PRIMARY:-eDP1}"

help() {
  echo "exd on|off"
}

connected-displays() {
  xrandr | grep " connected" | awk -F' ' '{ print $1 }'
}

on() {
  for display in $(connected-displays); do
    case $display in
      "$PRIMARY")
        echo "setting $display as primary"
        xrandr --output "$display" --primary
        ;;
      DP1)
        echo "turning $display on above $PRIMARY"
        xrandr --output "$display" --mode 1920x1080 --above eDP1
        ;;
    esac
  done
}

off() {
  for display in $(connected-displays); do
    case $display in
      DP1)
        echo "turning $display off"
        xrandr --output "$display" --off
        ;;
    esac
  done
}

$@
