#!/bin/sh

CLIP=

case $XDG_SESSION_TYPE in
  wayland)
    CLIP="wl-copy --paste-once"
    ;;
  *)
    CLIP="xclip -sel clip"
    ;;
esac

gopass ls --flat | bemenu -l 10 -i -n --line-height 35 \
  --fn "$(font) 12" \
  --nb '#16161d' \
  --tb '#16161d' \
  --fb '#16161d' \
  --hb '#16161d' \
  | xargs -I'{}' gopass show -o '{}' | $CLIP
