#!/bin/bash

get-branch() {
  git symbolic-ref -q HEAD | sed 's|refs/heads/||'
}

is-feature() {
  local BRANCH="$1"
  echo "$BRANCH" | grep -q "^features/"
}

get-feature-id() {
  local BRANCH="$1"
  echo "$BRANCH" | sed 's|^features/\([A-Z0-9]\+-[0-9]\+\)_.*|\1|g'
}

BRANCH=$(get-branch)
FEATURE="$(get-feature-id "$BRANCH")"

if is-feature "$BRANCH"; then
  if ! echo "$1" | grep -q "^$FEATURE"; then
    sed -i "1s/^/$FEATURE /" $1
  else
    echo $1
  fi
fi
