#!/bin/sh 
month () {
  case $@ in
    Januar) echo "1" ;;
    Februar) echo "2" ;;
    März) echo "3" ;;
    April) echo "4" ;;
    Mai) echo "5" ;;
    Juni) echo "6" ;;
    Juli) echo "7" ;;
    August) echo "8" ;;
    September) echo "9" ;;
    Oktober) echo "10" ;;
    November) echo "11" ;;
    Dezember) echo "12" ;;
  esac
}

date=$(date +'%d. %B %Y')
latex_folder=/data/Work/latex
rechnungs_folder=/data/Work/rechnungen
rechnungs_template="rechnung.tex"

wageperhour="12.00"

echo "Please enter the month: "
read month

echo "Please enter the year: "
read year

echo "Please enter the amount of hours worked: "
read hours

echo "Please enter the city you are in: "
read city

#pushd ./ >/dev/null
cur_folder=$(pwd)

cd $latex_folder

d_month=$(month "$month")
if [ -z $d_month ]; then
  rechnungs_file="$year-$month.tex"
else
  rechnungs_file="$year-$d_month.tex"
fi

cp $rechnungs_template $rechnungs_file

sed -i "s/\[DATE\]/$date/" $rechnungs_file
sed -i "s/\[HOURS\]/$hours/" $rechnungs_file
sed -i "s/\[WAGEPERHOUR\]/$wageperhour/" $rechnungs_file
sed -i "s/\[MONTH\]/$month/" $rechnungs_file
sed -i "s/\[YEAR\]/$year/" $rechnungs_file
sed -i "s/\[CITY\]/$city/" $rechnungs_file

pdflatex -output-directory $rechnungs_folder $rechnungs_file

rm $rechnungs_file
rm $rechnungs_folder/*.{aux,log}

#popd >/dev/null
cd $cur_folder

exit 0
