#!/bin/bash

[ $EUID -ne 0 ] && exit "Needs root to run"

confirm() {
  local ANSWER
  echo "$1" && read -r ANSWER

  case $ANSWER in
    y|Y|yes|Yes|YES)
      return 0 ;;
    *)
      return 1 ;;
  esac
}

eix-sync -w && eix-sync && eix-update

eselect news read

echo && confirm "continue? y/[n] " || exit 2

emerge -avuDN --with-bdeps y @world || exit 1

etc-update || exit 1

[ -x "$(command -v lafilefixer)" ] && lafilefixer --justfixit || exit 1

emerge -av --depclean || exit 1

revdep-rebuild || exit 1

eclean -d distfiles || exit 1
