#!/bin/bash

KVM=${KVM:-}

devices () {
    ip link | egrep "^[0-9]+" | awk -F':' '{ print $2 }'
}

find-kvm-vm () {
    local device="$1"

    [ -z "$device" ] && return

    for vm in $(virsh list | grep running | awk '{print $2}'); do
        virsh dumpxml $vm | grep -q "dev='$device'" && echo $vm && return
    done
}

mac () {
    local device="$1"

    ip link show dev "$device" | grep "link/ether" | awk -F' ' '{ print $2 }'
}

show-limits () {
    local device="$1"

    tc qdisc show dev "$device"
}

for device in $(devices); do
    MAC="$(mac "$device")"
    VM=

    if $KVM && [[ "$device" =~ "vnet" ]]; then
        VM="$(find-kvm-vm "$device")"
    fi

    echo "$device${MAC:+ $MAC}${VM:+ ($VM)}:"
    echo -e "$(show-limits "$device" | sed 's/^/\t/')"
done
