#!/bin/bash
# wconnect.sh -- created 2013-09-03, Aljosha Friemann
# @Last Change: 24-Dez-2004.
# @Revision:    0.0

checkhost="8.8.8.8"

ssid=""
wireless_device=""

verbosity="&>/dev/null"
quiet=false

dhcp="dhclient"

# Two dots :)
prefix="••"

# echo colours and format
greenecho () { 
  echo -e "\033[1;34m${prefix}\033[0m\033[1;32m $@\033[0m" 
}

redecho () { 
  echo -e "\033[1;34m${prefix}\033[0m\033[1;31m $@\033[0m" 
}

successecho () { 
  echo -e "\033[1;34m${prefix}\033[0m\033[1;38m $@\033[0m" 
}

failecho () { 
  echo -e "\033[1;34m${prefix}\033[0m\033[1;31m $@\033[0m" 
}

delimiter () {
  echo -e "\033[1;34m•••••••••••••••••••$@"
}

root () {
  if [ "$UID" != 0 ]; then 
    me=$(dirname $0)/$(basename $0)
    sudo $me $@
    exit 0
  fi

  return 0
}

run () {
  sudo=""
  if ! [ $2 ]; then
    sudo="sudo"
  fi

  sh -c "$sudo $1 $verbosity"
  return $?
}

detect_wireless_device () {
  saveIFS=$IFS

  IFS=$'\n' read wifi0 wifi1 wifi2 <<< "$(ip link | grep -o "w[a-z 0-9]*[0-9]")"

  if [ -z $wifi0 ]
  then
    redecho "can't auto detect wireless interface, please enter device name: "
    read wireless_device
    return 0
  fi

  if [ -z $wifi1 ]
  then
    wireless_device=$wifi0 
  else
    if [ -z $wifi2 ]
    then
      greenecho "available wireless interfaces: $wifi0 | $wifi1 - enter device name: "
    else
      greenecho "available wireless interfaces: $wifi0 | $wifi1 | $wifi2 - enter device name: "
    fi

    read wireless_device
  fi

  IFS=$saveIFS
  
  return 0
}

detect_ssid () {
  ssid=$(wpa_cli status | grep -e "ssid" | grep -v bssid | cut -d'=' -f2)
  return 0
}

wpa_supplicant_up () {
  run "pidof wpa_supplicant" 1
  return $?
}

dhcp_up () {
  run "pidof $dhcp" 1
  return $?
}

connect_wpa_supplicant () {
  if ! wpa_supplicant_up; then
    greenecho "starting wpa_supplicant.."
    run "wpa_supplicant -B -Dwext -c /etc/wpa_supplicant.conf -i $wireless_device"
    ret=$?
    if [ $ret -ne 0 -a $ret -ne 255 ]; then
      failecho "failed to start wpa_supplicant!"
    fi
    return $ret
  fi

  return 0
}

connect_dhcp () {
  greenecho "trying to get dhcp lease.."
  run "$dhcp -v $wireless_device"
  ret=$?
  if [ $ret -ne 0 ]; then
    failecho "failed to start $dhcp"
  fi
  return $ret
}

connect () {
  connect_wpa_supplicant
  connect_dhcp
  return $?
}

disconnect_dhcp () {
  greenecho "terminating $dhcp.."
  run "killall $dhcp"
  return $?
}

disconnect_wpa_supplicant () {
  greenecho "terminating wpa_supplicant.."
  #run "wpa_cli terminate"
  #ret=$?
  run "killall wpa_supplicant"
  return $?
}

disconnect () {
  disconnect_wpa_supplicant  
  disconnect_dhcp
}

connected () {
  #run "timeout -s KILL 2s ping -n -c1 -W1 $checkhost &>/dev/null" 1
  run "ping -n -c1 $checkhost" 1
  return $?
}

main () {
  greenecho "pinging $checkhost"
  if connected; then
    greenecho "already connected, try reconnecting if you really want to."
    exit 0
  else
    failecho "not connected!"
  fi

  greenecho "attempting to detect wireless interface.."
  if [ ! $wireless_device ]; then
    detect_wireless_device 
  fi
  successecho "set wireless device name to $wireless_device"

  tries=1
  success=false

  greenecho "trying to connect.."
  while [[ tries -lt 4 ]];
  do
    delimiter " $tries".
    if connect; then
      success=true
      break
    fi
    failecho "not connected!"
    disconnect
    let tries=tries+1
  done

  if $success; then
    detect_ssid
    successecho "connection established with $ssid, have fun!"
    return 0
  fi

  failecho "could not establish connection.."
  return 1
}

help () {
  echo -e "usage: wconnect [COMMANDS]\n
    possible commands are:\n 
    \t-h this help message
    \t-i specify interface
    \t-q quiet mode
    \t-r force reconnect 
    \t-v verbosity: [1] - stdout, 2 - stdout & stderr
    \t-x terminate connection\n"
}

while getopts "hi:qrvx" optname
do
  case "$optname" in
    "h")
      help
      exit 0
      ;;
    "i")
      wireless_device=$OPTARG
      ;;
    "q")
      quiet=true
      ;;
    "r")
      disconnect
      ;;
    "v")
      verbosity=""
      ;;
    "x")
      disconnect
      exit 0
      ;;
    "?")
      failecho "unknown option $OPTARG"
      exit 1
      ;;
    ":")
      failecho "no argument value for option $OPTARG"
      exit 1
      ;;
    *)
      # Should not occur
      failecho "unknown error while processing options"
      exit $?
      ;;
  esac
done


if $quiet; then
  main $@ &>/dev/null
else
  main $@
fi

exit 0
