#!/bin/bash

DOMAIN="$1"
CERT="$2"

if ! test -f "$CERT"; then
    echo "File does not exist: $CERT" && exit 1
fi

REMOTE_PIN=$(echo "Q" | openssl s_client -connect "$DOMAIN":443 -servername "$DOMAIN" 2>/dev/null | openssl x509 -pubkey -noout | openssl rsa -pubin -outform der 2>/dev/null | openssl dgst -sha256 -binary | openssl enc -base64)

LOCAL_PIN="$(< "$CERT" openssl x509 -pubkey -noout | openssl rsa -pubin -outform der 2>/dev/null | openssl dgst -sha256 -binary | openssl enc -base64)"

if test "$REMOTE_PIN" != "$LOCAL_PIN"; then
    echo "Pins do not match: $REMOTE_PIN != $LOCAL_PIN"
    exit 1
else
    echo "Pins match!"
fi
