#!/bin/bash

output() { echo -en "$@"; }

error() { output "\033[0;31m$@\033[0m"; }
success() { output "\033[0;32m$@\033[0m"; }
warning() { output "\033[0;33m$@\033[0m"; }

help() {
    echo -e "$0 install|search [PACKAGE]"
}

command=$1; shift

case $command in
    install)
        sudo xbps-install $@
        ;;
    search)
        xbps-query -vRs $@
        ;;
    remove)
        sudo xbps-remove $@
        ;;
    sync)
        sudo xbps-install -S
        ;;
    update)
        error "NOOOOPE" && exit 1
        ;;
    *)
        error "Unknown command: $*" && help && exit 1
        ;;
esac
